version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=consulta
      - DB_PASSWORD=root
      - DB_NAME=agendamento
      - DB_SERVER_PORT=3000
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendamento
      MYSQL_USER: consulta
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: